steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/uservote-api:$COMMIT_SHA", "."]
    env:
      - "LOG_LEVEL=${_LOG_LEVEL}"
      - "ENV=${_ENV}"
      - "DB_NAME=${_DB_NAME}"
      - "ATLAS_USERNAME=${_ATLAS_USERNAME}"
      - "ATLAS_PASSWORD=${_ATLAS_PASSWORD}"
      - "MAX_CONNECTIONS_COUNT=${_MAX_CONNECTIONS_COUNT}"
      - "MIN_CONNECTIONS_COUNT=${_MIN_CONNECTIONS_COUNT}"
  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/uservote-api:$COMMIT_SHA"]
  # Cloud run watches Artifact Registry for new images and automatically deploys them
images:
  - "gcr.io/$PROJECT_ID/uservote-api:$COMMIT_SHA"
