steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/uservote-api:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/uservote-api:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "uservote-api"
      - "--image=gcr.io/$PROJECT_ID/uservote-api:$COMMIT_SHA"
      - "--region=us-central1"
      - "--vpc-connector=uservote-vpc-connector"
      - "--vpc-egress=all-traffic"
      - --set-env-vars="LOG_LEVEL=${_LOG_LEVEL}"
      - --set-env-vars="ENV=${_ENV}"
      - --set-env-vars="DB_NAME=${_DB_NAME}"
      - --set-env-vars="ATLAS_USERNAME=${_ATLAS_USERNAME}"
      - --set-env-vars="ATLAS_PASSWORD=${_ATLAS_PASSWORD}"
      - --set-env-vars="MAX_CONNECTIONS_COUNT=${_MAX_CONNECTIONS_COUNT}"
      - --set-env-vars="MIN_CONNECTIONS_COUNT=${_MIN_CONNECTIONS_COUNT}"
images:
  - "gcr.io/$PROJECT_ID/uservote-api:$COMMIT_SHA"
